### PR TITLE
fix: sorting incorrectly after searching

### PR DESCRIPTION
**Pull request by Rui-Zhu1**
https://zenhub.ibm.com/workspaces/skills-network-6298c2c43568d9002bb68161/issues/skills-network/faculty/1560

### CODE REVIEW

**Review by arora-r — COMMENTED** [review]
Im sure this works but can you explain why changing the order makes it work?

Typically in a query to the db (for psql or SQL) the query is formed like this:

```
SELECT column1, column2,...columnN 
FROM table_name
[WHERE]
[GROUP BY]
[HAVING]
[ORDER BY column(s) [ASC|DESC]]
```

Where filtering (where clauses) are done first and sorting (order by) is done at the end.

**Comment by Rui-Zhu1** [comment]
I am not 100% sure. I guess it might because that the controller first sorts by status giving us a list of sorted quicklabs, and then it filters on that sorted list to find all the quicklabs that match the query string “test”, which might be resulting in an out-of-order string.

**Comment by arora-r** [comment]
> I am not 100% sure. I guess it might because that the controller first sorts by status giving us a list of sorted quicklabs, and then it filters on that sorted list to find all the quicklabs that match the query string “test”, which might be resulting in an out-of-order string.

By that logic, the order now would change to do sorting first then filter after.

Originally, we filter and then sort (https://github.com/ibm-skills-network/sn_filterable/blob/main/lib/sn_filterable/filterable.rb#L37-L39)

But the fix is supposedly sort then filter (https://github.com/ibm-skills-network/sn_filterable/pull/29/files#diff-e8aaf37ad37b9cd42091a00ee9b50489292bed3bb222636630a1b38fe08ef9a3R36-R38)

Im not sure how that helps.

**Comment by Rui-Zhu1** [comment]
This PR is to fix this code: https://github.com/ibm-skills-network/author-workbench/blob/3ae7dc100e309daa1f33b02792714b5147730c75/app/models/quicklab.rb#L100

1. In sn_filterable, it seems like that if we filter and then sort, which is what we are doing originally, pg_searcher_scope will take the sorted items and hash them, which will break the proper sorting we already have, which causes it to sort incorrectly.

2. But if we sort and then filter, sn_filterable will take the filtered items, which are hashed by pg_searcher_scope  first, and then sort them correctly.

**Review by arora-r — APPROVED** [review]

**Pull request merged**
